import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'

const quicksand = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KD Fotogrametria',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
